config/routes.rb
Rails.application.routes.draw do
	resources :user_sessions
	root :to => 'courses#index'
	get 'login' => 'user_sessions#new', :as => :login
	post 'logout' => 'user_sessions#destroy', :as => :logout
	resources :courses do
		member do
			get "results"
			get "statistics"
		end
  	resources :tests do
  		member do
  			get "scores"
  			post "scores", to: 'tests#update_scores'
  		end
  	end
  	resources :students
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  has_many :student_tests, :dependent => :delete_all
  validates :first_name, :last_name, :documet, :file, presence: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :set_course


  # GET /students
  # GET /students.json
  def index
    @students = @course.students.order(:last_name).all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = @course.students.build
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = @course.students.create(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to course_students_path(@course), notice: 'El alumno fue creado.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to course_students_path(@course), notice: 'El alumno fue actualizado' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to course_students_path(@course), notice: 'El alumno fue eliminado'}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    def set_course
      @course = Course.find(params[:course_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :file, :documet, :email, :course_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, url: [@course, @student], local: true, :html => { :class => "col-sm-4 form-horizontal" }, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> no permitieron guardar al alumno:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name, :class => 'control-label' %>
    <%= form.text_field :first_name, id: :student_first_name, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :last_name , :class => 'control-label'%>
    <%= form.text_field :last_name, id: :student_last_name, :class => 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :file , :class => 'control-label'%>
    <%= form.text_field :file, id: :student_file, :class => 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :documet, :class => 'control-label' %>
    <%= form.text_field :documet, id: :student_documet, :class => 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :email , :class => 'control-label'%>
    <%= form.text_field :email, id: :student_email, :class => 'form-control'  %>
  </div>

  <div class="form-group ">
    <div class="actions">
      <%= form.submit "Guardar", :class => 'btn btn-primary'%>
      <%= link_to 'Volver', course_students_path(@course), :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editando alumno para la cursada <%= @course.year %></h1>


<%= render 'form', student: @student %>

app/views/students/index.html.erb
<h1>Estudiantes de la cursada <%= @course.year %></h1>

<table  class="table table-striped">
  <thead>
    <tr>
      <th>Apellidos</th>
      <th>Nombres</th>
      <th>Legajo</th>
      <th>DNI</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.last_name %></td>
        <td><%= student.first_name %></td>
        <td><%= student.file %></td>
        <td><%= student.documet %></td>
        <td><%= student.email %></td>
        <td><%= link_to 'Editar', edit_course_student_path(@course, student) %></td>
        <td><%= link_to 'Eliminar', [@course, student], method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo estudiante', new_course_student_path, :class => 'btn btn-primary' %>

app/views/students/new.html.erb
<h1>Nuevo alumno para la cursada <%= @course.year %></h1>

<%= render 'form', student: @student %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>File:</strong>
  <%= @student.file %>
</p>

<p>
  <strong>Documet:</strong>
  <%= @student.documet %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Course:</strong>
  <%= @student.course %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>