config/routes.rb
Rails.application.routes.draw do
	resources :user_sessions
	root :to => 'courses#index'
	get 'login' => 'user_sessions#new', :as => :login
	post 'logout' => 'user_sessions#destroy', :as => :logout
	resources :courses do
		member do
			get "results"
			get "statistics"
		end
  	resources :tests do
  		member do
  			get "scores"
  			post "scores", to: 'tests#update_scores'
  		end
  	end
  	resources :students
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/user_sessions_controller.rb
# app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:courses, notice: 'Usuario logueado')
    else
      flash.now[:alert] = 'Login invalido'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(login_path, notice: 'Usuario deslogueado!')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post, class: "col-sm-4" do %>
  <div class="form-group">
    <div class="field">
      <%= label_tag :email, "Email", :class => 'control-label' %><br />
      <%= text_field_tag :email, nil, :class => 'form-control' %>
    </div>
    <div class="field">
      <%= label_tag :password, "Password", :class => 'control-label' %><br />
      <%= password_field_tag :password, nil, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="actions">
      <%= submit_tag "Ingresar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Iniciar sesion</h1>

<%= render 'form' %>